-- New international facilities (researched 2026-08): South Africa, Japan,
-- Philippines, Hong Kong, Brazil.
--   npx wrangler d1 execute gymmap --remote --file=migrations/0005_new_facilities.sql
INSERT INTO schools (id,name,type,categories,location,region,address,website,instagram,specialties,lat,lon,online,status,notes) VALUES
('dbbcfabe-6815-4cd5-975c-46289a6a437b','Stunt Network','Stunt Services & Training','["Stunt Training Facility","Wirework, Rigging & Aerial","Combat","Driving & Motorsports"]','Cape Town, SOUTH AFRICA','Africa','','https://stuntnetwork.co.za/','','["Fight Choreography","Wirework","Rigging","Stunt Driving","High Falls"]',-33.9249,18.4241,0,'published',''),
('69a53b89-a343-40aa-8055-2afb6ed069ec','South African Stunt Association (SASA)','Stunt Association — Workshops & Mentorship','["Combat","Driving & Motorsports"]','Johannesburg, SOUTH AFRICA','Africa','','https://www.sastuntcrew.co.za/','','["Fight Choreography","Stunt Driving"]',-26.2041,28.0473,0,'published',''),
('56b86ef8-0d3d-44eb-bcc0-fd68a8214a49','Bailey Bros Stunts & Rigging','Stunt Rigging','["Wirework, Rigging & Aerial"]','Cape Town, SOUTH AFRICA','Africa','','https://baileybros.co.za/','','["Rigging","Wirework","High Falls"]',-33.9249,18.4241,0,'published',''),
('8dd4304a-e6c8-4ad3-a57f-0413f8ec604f','Stunteam','Action Design & Performer Training','["Combat","Wirework, Rigging & Aerial"]','Cape Town, SOUTH AFRICA','Africa','','https://thestunteam.com/','','["Fight Choreography","Rigging","Screen Combat"]',-33.9249,18.4241,0,'published',''),
('b3280830-fae1-4eaa-b3f5-8763619dca2d','JAG Action Creator School (Japan Action Guild)','Action School','["Stunt School","Combat","Wirework, Rigging & Aerial"]','Tokyo, JAPAN','Asia-Pacific','','https://school.japanactionguild.jp/en/','','["Fight Choreography","Screen Combat","Wirework","Tumbling"]',35.6762,139.6503,0,'published',''),
('4bcb1898-a27c-476b-8e5d-1935047c8c6c','Quiet Flame Productions','Stunts & Martial Arts','["Combat","Stunt Training Facility"]','Roppongi, Tokyo, JAPAN','Asia-Pacific','','https://www.quietflame.org/','','["Martial Arts","Taekwondo","Screen Combat","Fight Choreography"]',35.6627,139.7292,0,'published',''),
('ad033ff5-505e-467d-8023-d4e5a3a4ea4c','Stuntworks Action Academy','Stunt Team & Academy','["Stunt School","Combat"]','Manila, PHILIPPINES','Asia-Pacific','','https://www.facebook.com/p/Stuntworks-Action-Academy-Philippines-100095260456159/','','["Fight Choreography","Martial Arts","High Falls"]',14.5995,120.9842,0,'published',''),
('3fa98bff-a217-4a54-8def-e7e9d3e5855c','New Era Martial Club','Action Stunts Academy','["Stunt Training Facility","Combat","Wirework, Rigging & Aerial","Firearms & Tactical"]','Quarry Bay, HONG KONG','Asia-Pacific','','','','["Fight Choreography","Wirework","Firearms","Martial Arts"]',22.2871,114.2115,0,'published',''),
('ced6c17e-d22f-47eb-8b42-14de658395c8','Centro de Treinamento Tático para Atores e Dublês','Stunt Training Center','["Stunt School","Combat","Fire Burns","Driving & Motorsports"]','São Paulo, BRAZIL','South America','Rua Santa Cruz, 1593 – Vila Mariana, São Paulo, Brazil','','','["Fight Choreography","Fire Burns","Car Hits","Stair Falls","Horse Stunts","Stunt Driving"]',-23.5896,-46.6347,0,'published',''),
('518c65b4-e113-478e-a8f7-a75d1de118cf','Action Kung Fu Dublês Marciais','Martial Arts Stunt Doubles','["Combat"]','São Paulo, BRAZIL','South America','','https://actionkungfu.com.br/','','["Martial Arts","Kung Fu","Fight Choreography"]',-23.5505,-46.6333,0,'published','');
