-- More international facilities (researched 2026-08): India, China, Mexico,
-- Argentina, Colombia. Adds the "Motorcycle Stunts" specialty (CDMX schools).
--   npx wrangler d1 execute gymmap --remote --file=migrations/0007_more_facilities.sql
INSERT INTO schools (id,name,type,categories,location,region,address,website,instagram,specialties,lat,lon,online,status,notes) VALUES
('65962e6b-92a7-4074-9a5d-5b56a26c87d5','Stunt Academy India (SAI)','Stunt Academy','["Stunt School","Fight Choreography"]','Mumbai, INDIA','Asia-Pacific','','','@stunt_academy_india','["Fight Choreography","Martial Arts","High Falls","Screen Combat"]',19.076,72.8777,0,'published',''),
('acc706e3-23bc-4012-bc62-68d0d84c23c2','Mumbai Movement Academy','Movement & Parkour','["Stunt Training Facility","Parkour"]','Mumbai, INDIA','Asia-Pacific','','https://www.mumbaimovementacademy.com/','','["Parkour","Tumbling","Martial Arts"]',19.1136,72.8697,0,'published',''),
('c54eb769-79a5-4d9c-bf62-bb3cfc69c37e','International Shaolin Dragon Academy','Stunt & Martial Arts School','["Stunt School","Fight Choreography"]','Dengfeng, Henan, CHINA','Asia-Pacific','','https://www.shaolinxl.com/study/stunt-training/','','["Fight Choreography","Martial Arts","Kung Fu","Screen Combat","Stage Combat"]',34.4536,113.0378,0,'published',''),
('539ea8a3-f87d-44a7-841f-8597f5610733','Hengdian World Studios — Performer Training','Studio Complex & Performer Training','["Stunt Training Facility","Fight Choreography"]','Hengdian, Zhejiang, CHINA','Asia-Pacific','','https://www.hengdian-fts.com/about','','["Fight Choreography","Martial Arts"]',29.15,120.2833,0,'published',''),
('eba3b082-b9ed-4819-a36d-c145d3d97ad5','Escuela Stunt Reyes MX','Motorcycle Stunt School','["Stunt School","Driving & Motorsports"]','Iztapalapa, Mexico City, MEXICO','Latin America','','https://www.facebook.com/stuntreyesmx/','@escuela_stunt_reyesmx','["Motorcycle Stunts"]',19.3574,-99.0741,0,'published',''),
('613ce0eb-d576-483c-99a5-dea32f93fdae','Stunt Street MX','Motorcycle Stunt School','["Stunt School","Driving & Motorsports"]','Mexico City, MEXICO','Latin America','','https://www.facebook.com/stuntstreetmxoficial/','','["Motorcycle Stunts"]',19.4326,-99.1332,0,'published',''),
('820a36b7-dda9-4f48-903c-d8e35984641c','Fiction Stunt','Stunt School','["Stunt School","Fight Choreography"]','Lanús, Buenos Aires, ARGENTINA','South America','Monte Chingolo, Lanús, Buenos Aires, Argentina','','','["Fight Choreography","Screen Combat","Tumbling"]',-34.7206,-58.3906,0,'published',''),
('8db63efd-39d0-4d5c-8db9-49abeee951df','Stunt Sudamérica','Stunt School & Seminars','["Stunt School","Fight Choreography"]','Buenos Aires, ARGENTINA','South America','','','','["Fight Choreography","High Falls","Screen Combat"]',-34.6037,-58.3816,0,'published',''),
('7246f2ea-7aa2-4a53-be0d-d5f13b69a708','FX Argentina — Stunts','Stunt Team & Actor Training','["Fight Choreography"]','Buenos Aires, ARGENTINA','South America','','https://fxargentina.com/stunts/','','["Fight Choreography","Martial Arts"]',-34.6118,-58.4173,0,'published',''),
('97a5cae7-699e-44c0-b4e2-6c38f1085b30','Colombia Stuntmen Association (CSTA)','Stunt Academy','["Stunt School","Fight Choreography"]','Bogotá, COLOMBIA','South America','','','','["Fight Choreography","Martial Arts","High Falls"]',4.711,-74.0721,0,'published','');
