// Database migrations that ship with the Worker and apply themselves.
//
// On the first request after a deploy the Worker checks the _migrations ledger
// and runs anything new, exactly once, then never touches it again. That means
// a code deploy is all it takes to move the schema forward — no CLI step.
//
// Migrations 0001-0006 were the manual bootstrap (see README); a brand-new
// database still needs those applied once before this list takes over.
export const MIGRATIONS = [
  {
    id: "0007_more_facilities",
    statements: [
      "INSERT OR IGNORE INTO schools (id,name,type,categories,location,region,address,website,instagram,specialties,lat,lon,online,status,notes) VALUES\n('65962e6b-92a7-4074-9a5d-5b56a26c87d5','Stunt Academy India (SAI)','Stunt Academy','[\"Stunt School\",\"Fight Choreography\"]','Mumbai, INDIA','Asia-Pacific','','','@stunt_academy_india','[\"Fight Choreography\",\"Martial Arts\",\"High Falls\",\"Screen Combat\"]',19.076,72.8777,0,'published',''),\n('acc706e3-23bc-4012-bc62-68d0d84c23c2','Mumbai Movement Academy','Movement & Parkour','[\"Stunt Training Facility\",\"Parkour\"]','Mumbai, INDIA','Asia-Pacific','','https://www.mumbaimovementacademy.com/','','[\"Parkour\",\"Tumbling\",\"Martial Arts\"]',19.1136,72.8697,0,'published',''),\n('c54eb769-79a5-4d9c-bf62-bb3cfc69c37e','International Shaolin Dragon Academy','Stunt & Martial Arts School','[\"Stunt School\",\"Fight Choreography\"]','Dengfeng, Henan, CHINA','Asia-Pacific','','https://www.shaolinxl.com/study/stunt-training/','','[\"Fight Choreography\",\"Martial Arts\",\"Kung Fu\",\"Screen Combat\",\"Stage Combat\"]',34.4536,113.0378,0,'published',''),\n('539ea8a3-f87d-44a7-841f-8597f5610733','Hengdian World Studios — Performer Training','Studio Complex & Performer Training','[\"Stunt Training Facility\",\"Fight Choreography\"]','Hengdian, Zhejiang, CHINA','Asia-Pacific','','https://www.hengdian-fts.com/about','','[\"Fight Choreography\",\"Martial Arts\"]',29.15,120.2833,0,'published',''),\n('eba3b082-b9ed-4819-a36d-c145d3d97ad5','Escuela Stunt Reyes MX','Motorcycle Stunt School','[\"Stunt School\",\"Driving & Motorsports\"]','Iztapalapa, Mexico City, MEXICO','Latin America','','https://www.facebook.com/stuntreyesmx/','@escuela_stunt_reyesmx','[\"Motorcycle Stunts\"]',19.3574,-99.0741,0,'published',''),\n('613ce0eb-d576-483c-99a5-dea32f93fdae','Stunt Street MX','Motorcycle Stunt School','[\"Stunt School\",\"Driving & Motorsports\"]','Mexico City, MEXICO','Latin America','','https://www.facebook.com/stuntstreetmxoficial/','','[\"Motorcycle Stunts\"]',19.4326,-99.1332,0,'published',''),\n('820a36b7-dda9-4f48-903c-d8e35984641c','Fiction Stunt','Stunt School','[\"Stunt School\",\"Fight Choreography\"]','Lanús, Buenos Aires, ARGENTINA','South America','Monte Chingolo, Lanús, Buenos Aires, Argentina','','','[\"Fight Choreography\",\"Screen Combat\",\"Tumbling\"]',-34.7206,-58.3906,0,'published',''),\n('8db63efd-39d0-4d5c-8db9-49abeee951df','Stunt Sudamérica','Stunt School & Seminars','[\"Stunt School\",\"Fight Choreography\"]','Buenos Aires, ARGENTINA','South America','','','','[\"Fight Choreography\",\"High Falls\",\"Screen Combat\"]',-34.6037,-58.3816,0,'published',''),\n('7246f2ea-7aa2-4a53-be0d-d5f13b69a708','FX Argentina — Stunts','Stunt Team & Actor Training','[\"Fight Choreography\"]','Buenos Aires, ARGENTINA','South America','','https://fxargentina.com/stunts/','','[\"Fight Choreography\",\"Martial Arts\"]',-34.6118,-58.4173,0,'published',''),\n('97a5cae7-699e-44c0-b4e2-6c38f1085b30','Colombia Stuntmen Association (CSTA)','Stunt Academy','[\"Stunt School\",\"Fight Choreography\"]','Bogotá, COLOMBIA','South America','','','','[\"Fight Choreography\",\"Martial Arts\",\"High Falls\"]',4.711,-74.0721,0,'published','')"
    ],
  },
  {
    id: "0008_facility_type",
    statements: [
      "ALTER TABLE schools ADD COLUMN facility_type TEXT NOT NULL DEFAULT 'Stunt Training Facility'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='01b846b2-41cb-41c7-86f1-cb3a8138e277'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='024929ce-529f-4083-98e0-c0e3bfb9fbe8'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Kids Programs\",\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='0e5d5aa8-7caf-4875-ae4d-4a45e496b89a'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Motion Capture & Previs\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='1a542823-e5ec-4089-b256-54948fc58590'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='1cd817b6-8966-4eec-aca6-828f8c7668c1'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Wirework, Rigging & Aerial\",\"Fire Burns\",\"Fight Choreography\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='1e1d9682-6a0c-4c91-baf2-44a3c2f40a31'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Firearms & Tactical\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='2594aaf7-531c-44c4-9869-102e19dd27df'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='2a758fec-25f9-405c-97df-312de8be67d9'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='3267bd43-664c-459b-b361-8490e93a6cd2'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='3f6e24af-5825-473b-bd0f-9d91085674f2'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='492dd254-af21-4f71-9dbe-a7a91509a98e'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='4c4e3697-cf97-4190-85b9-29e052c9e07c'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Parkour\",\"Fight Choreography\",\"Driving & Motorsports\",\"Fire Burns\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='58c3f283-729b-4869-913a-0b226a347459'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='5e1f0b82-a8d5-4d33-a449-cd374079e772'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='60759f13-7e37-4e32-8ca2-cab282fa90b3'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Motion Capture & Previs\"]', updated_at=datetime('now') WHERE id='614aecf8-6923-4e30-b698-69b7294dd14c'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='66a708dd-c588-402e-969c-695977e1021b'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='6b1dc22a-8cdb-49d7-9728-846765cd4ab1'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='8aaa8a39-0fcb-4407-aeeb-50d9012a2c74'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='8e8decee-26a4-4ec3-9719-0fd4aec37936'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Kids Programs\",\"Fight Choreography\",\"Firearms & Tactical\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='8fe7295c-744d-4aab-8c5d-7e36d3920a51'",
      "UPDATE schools SET facility_type='Open Gym', categories='[\"Kids Programs\",\"Fight Choreography\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='a59af5f8-f596-4e41-a465-5fc6774264b6'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='a71d2b41-9972-417f-baa4-d62c8fd28cca'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='ad7af939-0df4-4f79-b067-fd7c2102b291'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='b2b39f5c-d7cf-47a5-85aa-e098c74e6557'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='b903fcdd-d278-480a-acb3-04e44c92e0d9'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='c2c7249e-b36c-4e09-8426-e82b9a3e5356'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='c7d5e9a1-7672-4224-99d9-bf808ec29ecb'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='cce0749b-c3f8-43f2-b2a1-33212207da74'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='cd54cd21-762a-45a4-97fc-827119a2ffdd'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Motion Capture & Previs\"]', updated_at=datetime('now') WHERE id='cd6f9c04-f962-46be-89a6-0e316a162276'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='ce886494-3f78-4fe3-becf-9e3934e4aa5f'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='cf87e3ed-083e-48cf-8b22-eae003a699bd'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='d5a0c516-a573-4be5-8616-598b3be2e202'",
      "UPDATE schools SET facility_type='Open Gym', categories='[\"Parkour\",\"Kids Programs\",\"Fight Choreography\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='d8fa7705-95d4-42aa-b488-695a56a89b85'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='e4850d06-cf2b-463b-921e-a69ac5869dfb'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='ea632dab-03fb-4891-93ad-b4d67a5f328f'",
      "UPDATE schools SET facility_type='Open Gym', categories='[\"Parkour\",\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='f7945e80-cb41-4649-9e96-7c0328e80278'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Parkour\",\"Fight Choreography\",\"Fire Burns\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='fca26bae-7097-47db-bb6a-99039654f52a'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='169bdfdc-829e-4cf8-8625-853c1abb830f'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='1dd3cc7d-5552-4919-a37b-8c2bf89a5412'",
      "UPDATE schools SET facility_type='Open Gym', categories='[]', updated_at=datetime('now') WHERE id='2319b3ca-509b-4b06-a7c5-031dcbaaea9c'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='2a1ab9c0-3273-428e-bc80-244316f07e21'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\"]', updated_at=datetime('now') WHERE id='2ab3f541-89be-4077-9474-c3b43e879d33'",
      "UPDATE schools SET facility_type='Open Gym', categories='[\"Parkour\",\"Fight Choreography\",\"Motion Capture & Previs\"]', updated_at=datetime('now') WHERE id='2d9bbea2-ff3e-4360-891f-47f8a2861fb3'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Wirework, Rigging & Aerial\",\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='349a1b0d-95eb-4c62-8189-9f0cbfae8118'",
      "UPDATE schools SET facility_type='Open Gym', categories='[\"Kids Programs\",\"Fight Choreography\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='34d85440-cd04-46c1-a59d-c41cac1c7797'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='41ba28b2-95d0-428a-91a8-489e9893c205'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='45c94cda-84c6-40ca-9d14-b236123030e9'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='4acba4cd-bb71-4cc0-a0d5-51e85fefe2b7'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='56c7b5d3-f17f-4dbe-8fc5-7ea088c41ada'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='5a3cc568-cbfd-4b06-9c1e-a5f63ee1ceef'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Wirework, Rigging & Aerial\",\"Fight Choreography\",\"Kids Programs\"]', updated_at=datetime('now') WHERE id='5d6d5705-3488-4305-8e91-493281f71988'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='617334d6-0f27-44fd-807d-105f7c9976d1'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='686f5ac1-8cea-4c02-91eb-d41bf768107b'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='739fce78-5ed7-4d21-8905-c8244f9cb1f4'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\"]', updated_at=datetime('now') WHERE id='77fc85b7-c3e3-416b-9bc5-532c07f7c2b5'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='780b233e-1e90-4bb2-a12a-076a1acee735'",
      "UPDATE schools SET facility_type='Open Gym', categories='[\"Parkour\",\"Fight Choreography\",\"Kids Programs\"]', updated_at=datetime('now') WHERE id='817c10b3-b988-40bd-aedc-f646e72f7133'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Wirework, Rigging & Aerial\",\"Fire Burns\",\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='87e44e51-01dc-4364-b2d2-0685f144f888'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\",\"Firearms & Tactical\",\"Fire Burns\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='90bb4a5f-9461-435d-9e15-cdeba8a38e94'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='97734294-8e0b-4475-81d6-40099d436fa9'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='a2bd9e02-47a4-4a19-b018-485a6c9ebbc2'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='a3240f1f-88c1-496a-89c6-f23439bb36b5'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Firearms & Tactical\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='ac18ede5-faa6-40af-873e-16fcd9f3dcc6'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='b4708f9b-a4ce-4859-b24e-a8d58e7069bc'",
      "UPDATE schools SET facility_type='Open Gym', categories='[\"Wirework, Rigging & Aerial\",\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='c1e72042-6a76-4ecf-9902-fe6d15d6bd9a'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\"]', updated_at=datetime('now') WHERE id='c26a0b1a-679b-4ce7-a59a-ea1a950c243c'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='c3a07b5e-c071-4bee-a6e8-a5a97ae6d009'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='d4b6fc15-bf31-47bb-9453-eb692ab9e479'",
      "UPDATE schools SET facility_type='Open Gym', categories='[]', updated_at=datetime('now') WHERE id='d6453a2f-2823-4d6e-be90-5d88a42efe00'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='e03d105d-69ea-44b5-b60b-8f040fe47568'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Motion Capture & Previs\"]', updated_at=datetime('now') WHERE id='e0a1a3f4-eea5-4052-87cb-e9361a2f2265'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Kids Programs\",\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='e4f74858-8fdd-4638-98fe-c5e76152aadc'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='e51c503f-f33c-4c92-af58-1384be795197'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Parkour\",\"Fight Choreography\",\"Motion Capture & Previs\",\"Fire Burns\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='e7847256-fb93-4e27-aa1a-c469189629e0'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='eb0b8a94-ab20-4470-8dd2-10afbfd94f43'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='ecb04c92-9d62-4988-9040-eaedce2a7d1c'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='04f5227e-54cf-4d71-831e-5620f6fbf3b2'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Parkour\",\"Fight Choreography\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='09cf11ee-82af-4056-8e58-4fffdc02b7e6'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='0cba40c9-9b6c-4636-b175-9435278b4396'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\"]', updated_at=datetime('now') WHERE id='1b3b1b6b-8df6-408e-a3a9-9f4cb3b14161'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Horse Stunts\"]', updated_at=datetime('now') WHERE id='212c36e8-1be5-4b2a-b47d-e4c6f8356989'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Kids Programs\"]', updated_at=datetime('now') WHERE id='234c6666-5fb9-4947-8bef-3e48bd533309'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='2370c295-ca44-49b0-923c-5d380e434f75'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='241df1ec-81b0-4bb1-af7f-dc8178f06597'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='3abd144c-abbc-4a6d-b2dd-297229ae0f00'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Parkour\",\"Fight Choreography\",\"Firearms & Tactical\",\"Driving & Motorsports\",\"Fire Burns\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='4453e2d5-074d-413d-bcb9-a5b7134a82cd'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='45ca6654-3aa4-4131-86a4-75a91d0242c0'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='4c0d938c-e1a9-4d19-b264-57524dda5493'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\"]', updated_at=datetime('now') WHERE id='4f9ccea1-6101-47c3-a52b-beaf5cf97e76'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='5bc2db96-31e7-49fa-a22d-7e8066b2abd1'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='5ff04cd1-18f6-4c7e-b87e-1383149648c7'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Driving & Motorsports\",\"Fire Burns\"]', updated_at=datetime('now') WHERE id='629a1841-dfdc-438c-aa05-868958afbb7a'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='6587966d-6f60-41cf-910e-8494764e61a5'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='6edbeb22-e132-4ad1-878f-31ad90f019ba'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Kids Programs\",\"Fight Choreography\",\"Firearms & Tactical\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='77d7acc5-e54e-47a9-a29b-232df6aeb621'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Motion Capture & Previs\"]', updated_at=datetime('now') WHERE id='78dd61f4-4e73-466c-8179-4c4258357c21'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Wirework, Rigging & Aerial\",\"Fight Choreography\",\"Driving & Motorsports\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='878278bf-ed2f-47fc-9b31-fb30572ca002'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='8a7801f1-42a4-43e9-b829-ec64a5cb9917'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='8ad11044-f941-47b1-95df-c450d93e55fd'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='976e250d-77ea-4c0a-93b9-d55e63cefdcf'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='9a13daa5-087c-41f7-9815-6d05f79ada2f'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='a14b1a1e-a0a3-4301-b31c-30feefa90c21'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='b096af32-c60d-45d1-80e3-b3d3b8fd36f6'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Kids Programs\",\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='b22d66fc-05af-491a-a29a-02c659e585ed'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Wirework, Rigging & Aerial\",\"Fight Choreography\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='b2d6bbff-bb7d-41e4-8309-105a06a27440'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='c7912e3f-8e63-4196-9c8c-98a3db48aeb1'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='d9b472af-08de-48fd-88e5-ccd5445439c3'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Kids Programs\",\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='dc112412-1bfe-442f-be8a-6ea57941d261'",
      "UPDATE schools SET facility_type='Open Gym', categories='[\"Parkour\",\"Kids Programs\",\"Fight Choreography\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='e7fbbc1a-6189-4df4-8188-fb9687f4ac26'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='e879164e-2f62-4cd9-8d9f-2b86b0ef3663'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='edf07403-9cac-4705-a56e-725c1f9b1b8d'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Motion Capture & Previs\"]', updated_at=datetime('now') WHERE id='f2fd3571-e571-4e15-ac1c-08741108e557'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='f7390f3c-ad7a-4f56-8dd3-dbe1df0097fb'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='f8a5f9a6-10b1-40c9-99a8-0afe728dcdbd'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Motion Capture & Previs\"]', updated_at=datetime('now') WHERE id='ffeda943-5bba-4aa1-8d95-3cfe1b1e9ec7'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Motion Capture & Previs\"]', updated_at=datetime('now') WHERE id='05537a31-d4d7-45de-9439-b9e3b1b217c0'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='0e673306-1ad4-4420-ab57-3b43c1c2d74a'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='1a2b0a3e-b014-46a7-8037-8b5bed8a401f'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Wirework, Rigging & Aerial\",\"Fire Burns\",\"Fight Choreography\",\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='1dfd3385-1d38-4a9c-8adc-dd1dd78855bd'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='28ff3a05-2d52-4c46-ac30-4cbc0c29a909'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='3116c906-5658-481f-9d1e-d4e5e9740795'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\",\"Firearms & Tactical\",\"Fire Burns\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='36224f90-5c67-4c26-8dd4-4c91b6182807'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Wirework, Rigging & Aerial\",\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='3a73bfb8-ecbe-4561-a760-dabb142112ee'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Wirework, Rigging & Aerial\",\"Fire Burns\",\"Fight Choreography\",\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='3c4ac474-b13a-4e56-af06-9b8d3285e71f'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='3dc922bb-695c-441b-8eaa-1ef327f5e87d'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Parkour\",\"Fight Choreography\",\"Firearms & Tactical\",\"Driving & Motorsports\",\"Fire Burns\",\"Horse Stunts\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='416b0393-f726-4d78-9cc0-7e0ce47aaa94'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\",\"Fire Burns\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='41d1ca85-349e-4958-9b2b-1d244942e1b0'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Parkour\",\"Fight Choreography\",\"Firearms & Tactical\",\"Driving & Motorsports\",\"Fire Burns\",\"Horse Stunts\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='4dd05dda-8655-4135-bcf0-bff5c2da0dae'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='4f41b465-1f99-4f3a-964a-4388a919df9a'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\",\"Driving & Motorsports\",\"Fire Burns\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='518d5dd7-7533-4d82-be4b-71c5210cfe22'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='5b0b4bf4-bf19-46ec-94d0-c689f351befa'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Wirework, Rigging & Aerial\",\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='62065a31-c37e-4a1d-b04f-2d5365d73419'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Kids Programs\",\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='6aa2eb3f-d6af-438c-8077-68464cfcc4aa'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Horse Stunts\"]', updated_at=datetime('now') WHERE id='9743746f-9dce-4986-8fb5-f6ac279ecaa5'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='9c08b8fb-32f7-4a48-b487-bbb318d00642'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\",\"Firearms & Tactical\",\"Fire Burns\",\"Horse Stunts\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='9fa1ce21-6180-4968-b5e6-2d01ef7c813b'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='a11a6445-2f67-44d8-904f-c3220596b7b7'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Parkour\",\"Fight Choreography\",\"Firearms & Tactical\",\"Driving & Motorsports\",\"Fire Burns\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='b338c641-5c6d-4a03-ba7d-9758e35c8b87'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='b5a03720-a488-41e9-b1a5-a33130551431'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Wirework, Rigging & Aerial\",\"Fight Choreography\",\"Fire Burns\"]', updated_at=datetime('now') WHERE id='b767ba78-4aa7-438a-86d2-522efc8f314a'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\",\"Driving & Motorsports\",\"Firearms & Tactical\",\"Fire Burns\",\"Horse Stunts\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='b955e7e7-710b-4367-a796-a7fc6a3b4182'",
      "UPDATE schools SET facility_type='Open Gym', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='bae194e6-ab07-46ae-b609-ea7bf84fb6ae'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Parkour\",\"Fight Choreography\",\"Driving & Motorsports\",\"Firearms & Tactical\",\"Fire Burns\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='c5eb9a2a-485f-4d84-889a-d73cdd4e144d'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\",\"Firearms & Tactical\",\"Fire Burns\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='db51a398-6210-4e94-8436-118ef61834ca'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fire Burns\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='de569663-0508-4cb3-b88a-fadb4d712c24'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\",\"Firearms & Tactical\",\"Driving & Motorsports\",\"Fire Burns\",\"Horse Stunts\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='df4fc09f-f2ab-405e-93f6-d32682702eee'",
      "UPDATE schools SET facility_type='Stunt School', categories='[]', updated_at=datetime('now') WHERE id='e28f52f5-5dd2-4542-8777-e74eec1cac76'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='e5f59c68-464c-43c0-9192-ef53df69b5a2'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='e677f3d8-a1db-410c-b3f3-6f5cad615b8f'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='eef859dc-5e75-4628-a2ba-d85ae0607ca5'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='f4b272af-710a-4c22-9873-e07df4e2c813'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Firearms & Tactical\",\"Fire Burns\",\"Fight Choreography\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='fab919a8-6ca5-4713-9001-4785d453c415'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='fca0357d-7329-4263-8dfe-c3913d200c1b'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Kids Programs\",\"Fight Choreography\",\"Firearms & Tactical\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='ffb41816-50ae-469a-8531-4dd94661c3ca'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='c157be8e-3540-43b4-8390-de95e9deea6c'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='855a8c52-583d-4509-bf7b-39cf170121dd'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Wirework, Rigging & Aerial\",\"Fight Choreography\",\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='dbbcfabe-6815-4cd5-975c-46289a6a437b'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='69a53b89-a343-40aa-8055-2afb6ed069ec'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='56b86ef8-0d3d-44eb-bcc0-fd68a8214a49'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='8dd4304a-e6c8-4ad3-a57f-0413f8ec604f'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\",\"Wirework, Rigging & Aerial\"]', updated_at=datetime('now') WHERE id='b3280830-fae1-4eaa-b3f5-8763619dca2d'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='4bcb1898-a27c-476b-8e5d-1935047c8c6c'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='ad033ff5-505e-467d-8023-d4e5a3a4ea4c'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\",\"Wirework, Rigging & Aerial\",\"Firearms & Tactical\"]', updated_at=datetime('now') WHERE id='3fa98bff-a217-4a54-8def-e7e9d3e5855c'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\",\"Fire Burns\",\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='ced6c17e-d22f-47eb-8b42-14de658395c8'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='518c65b4-e113-478e-a8f7-a75d1de118cf'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='65962e6b-92a7-4074-9a5d-5b56a26c87d5'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Parkour\"]', updated_at=datetime('now') WHERE id='acc706e3-23bc-4012-bc62-68d0d84c23c2'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='c54eb769-79a5-4d9c-bf62-bb3cfc69c37e'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='539ea8a3-f87d-44a7-841f-8597f5610733'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='eba3b082-b9ed-4819-a36d-c145d3d97ad5'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Driving & Motorsports\"]', updated_at=datetime('now') WHERE id='613ce0eb-d576-483c-99a5-dea32f93fdae'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='820a36b7-dda9-4f48-903c-d8e35984641c'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='8db63efd-39d0-4d5c-8db9-49abeee951df'",
      "UPDATE schools SET facility_type='Stunt Training Facility', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='7246f2ea-7aa2-4a53-be0d-d5f13b69a708'",
      "UPDATE schools SET facility_type='Stunt School', categories='[\"Fight Choreography\"]', updated_at=datetime('now') WHERE id='97a5cae7-699e-44c0-b4e2-6c38f1085b30'"
    ],
  },
];
